name: perps_gamified
description: Gamified perpetual trading app

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core dependencies
  cupertino_icons: ^1.0.6
  
  # Blockchain & Wallet
  starknet: ^0.2.1
  web3dart: ^2.7.2
  
  # State Management
  provider: ^6.1.1
  
  # Networking
  dio: ^5.4.0
  web_socket_channel: ^2.4.0
  
  # Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # UI & Animations
  lottie: ^3.0.0
  confetti: ^0.7.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_animate: ^4.3.0
  
  # Utilities
  intl: ^0.18.1
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  flutter_secure_storage: ^9.0.0
  
  # Swipe Cards
  flutter_card_swiper: ^6.0.0
  
  # Charts (for ecosystem view)
  fl_chart: ^0.65.0
  
  # Haptics
  haptic_feedback: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
    
  fonts:
    - family: Clash
      fonts:
        - asset: assets/fonts/ClashDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/ClashDisplay-Semibold.ttf
          weight: 600
        - asset: assets/fonts/ClashDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/ClashDisplay-Regular.ttf
          weight: 400